base:
  random_state: 42
data:
  dataset_csv: 'dvc_repo/data/raw/iris.csv'
  features_path: 'dvc_repo/data/processed/features_iris.csv'
  train_dataset_path: 'dvc_repo/data/processed/train_iris.csv'
  test_dataset_path: 'dvc_repo/data/processed/test_iris.csv'
  test_size: 0.2
train:
  clf_params:
    'C' : 0.001 
    'solver' : 'lbfgs' 
    'multi_class' : 'multinomial' 
    'max_iter' : 100
  model_path: 'dvc_repo/models/model.joblib'

reports:
  metrics_file: 'dvc_repo/reports/metrics.json'
  confusion_matrix_image: 'dvc_repo/reports/confusion_matrix.png'