base:
  random_state: 42
data:
  dataset_csv: 'data/raw/iris.csv'
  features_path: 'data/processed/features_iris.csv'
  train_dataset_path: 'data/processed/train_iris.csv'
  test_dataset_path: 'data/processed/test_iris.csv'
  test_size: 0.2
train:
  clf_params:
    'C' : 0.1 
    'solver' : 'lbfgs' 
    'multi_class' : 'multinomial' 
    'max_iter' : 100
  model_path: 'models/model.joblib'

reports:
  metrics_file: 'reports/metrics.json'
  confusion_matrix_image: 'reports/confusion_matrix.png'